#!/usr/bin/env node
// Dependency license audit. Reads package-lock.json (every resolved package, direct and transitive) plus each installed
// package.json for the license field, and writes docs/DEPENDENCY-LICENSES.md.
//   node scripts/license-audit.mjs            regenerate docs/DEPENDENCY-LICENSES.md
//   node scripts/license-audit.mjs --check    fail when a license is not on the allowlist, is missing, or the document is stale
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const check = process.argv.includes("--check");

// Permissive licenses compatible with an MIT-licensed public release. Anything else needs a human decision.
const ALLOWED = new Set(["MIT", "ISC", "BSD-2-Clause", "BSD-3-Clause", "Apache-2.0", "0BSD", "BlueOak-1.0.0", "CC0-1.0", "Unlicense", "Python-2.0", "CC-BY-4.0", "MIT-0", "Zlib"]);
// Weak-copyleft licenses are accepted for build-time only tooling and are listed separately for review.
const REVIEW = new Set(["MPL-2.0", "LGPL-3.0-or-later", "LGPL-2.1-or-later"]);

const lock = JSON.parse(readFileSync(join(root, "package-lock.json"), "utf8"));
const rootPkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const rows = [];
for (const [path, meta] of Object.entries(lock.packages ?? {})) {
  if (!path.startsWith("node_modules/")) continue;
  const name = path.replace(/^.*node_modules\//, "");
  let license = meta.license;
  const installed = join(root, path, "package.json");
  if (!license && existsSync(installed)) {
    const j = JSON.parse(readFileSync(installed, "utf8"));
    license = typeof j.license === "string" ? j.license : j.license?.type ?? (Array.isArray(j.licenses) ? j.licenses.map((l) => l.type).join(" OR ") : undefined);
  }
  rows.push({ name, version: meta.version, license: license ?? "UNKNOWN", dev: Boolean(meta.dev), optional: Boolean(meta.optional) });
}
rows.sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));

const tokens = (expr) => expr.replace(/[()]/g, " ").split(/\s+(?:OR|AND)\s+|\s+/).map((t) => t.trim()).filter((t) => t && t !== "OR" && t !== "AND");
// For "A OR B" any allowed alternative suffices; for "A AND B" every part must be allowed.
function classify(expr) {
  if (expr === "UNKNOWN") return "unknown";
  const ors = expr.replace(/[()]/g, "").split(/\s+OR\s+/);
  const verdicts = ors.map((alt) => (alt.split(/\s+AND\s+/).every((t) => ALLOWED.has(t.trim())) ? "allowed" : alt.split(/\s+AND\s+/).every((t) => ALLOWED.has(t.trim()) || REVIEW.has(t.trim())) ? "review" : "blocked"));
  if (verdicts.includes("allowed")) return "allowed";
  if (verdicts.includes("review")) return "review";
  return "blocked";
}
void tokens;

const counts = new Map();
for (const r of rows) counts.set(r.license, (counts.get(r.license) ?? 0) + 1);
const problems = rows.filter((r) => classify(r.license) !== "allowed");

const lines = [];
lines.push("# Dependency licenses");
lines.push("");
lines.push("Generated by `node scripts/license-audit.mjs` from `package-lock.json` and the installed packages. Do not edit by hand; run the script and commit the result.");
lines.push("");
lines.push(`Project license: ${rootPkg.license}. Packages audited: ${rows.length} (${rows.filter((r) => !r.dev).length} runtime, ${rows.filter((r) => r.dev).length} development-only).`);
lines.push("");
lines.push("## License summary");
lines.push("");
lines.push("| License | Packages | Status |");
lines.push("| --- | --- | --- |");
for (const [license, n] of [...counts.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))) lines.push(`| ${license} | ${n} | ${classify(license)} |`);
lines.push("");
lines.push("## Packages needing review");
lines.push("");
if (problems.length === 0) lines.push("None: every package carries a license on the permissive allowlist.");
else {
  lines.push("| Package | Version | License | Scope | Status |");
  lines.push("| --- | --- | --- | --- | --- |");
  for (const r of problems) lines.push(`| ${r.name} | ${r.version} | ${r.license} | ${r.dev ? "dev" : "runtime"} | ${classify(r.license)} |`);
}
lines.push("");
lines.push("## All packages");
lines.push("");
lines.push("| Package | Version | License | Scope |");
lines.push("| --- | --- | --- | --- |");
for (const r of rows) lines.push(`| ${r.name} | ${r.version} | ${r.license} | ${r.dev ? "dev" : r.optional ? "runtime (optional)" : "runtime"} |`);
lines.push("");
const document = lines.join("\n");
const target = join(root, "docs/DEPENDENCY-LICENSES.md");

if (check) {
  const blocked = problems.filter((r) => !r.dev || classify(r.license) !== "review");
  const stale = !existsSync(target) || readFileSync(target, "utf8") !== document;
  if (blocked.length > 0) {
    for (const r of blocked) console.error(`license-audit: ${r.name}@${r.version} has license "${r.license}" (${classify(r.license)})`);
  }
  if (stale) console.error("license-audit: docs/DEPENDENCY-LICENSES.md is stale; run `node scripts/license-audit.mjs` and commit it");
  if (blocked.length > 0 || stale) process.exit(1);
  console.log(`license-audit: ${rows.length} packages, all permissive or dev-only review items; document is current`);
} else {
  writeFileSync(target, document);
  console.log(`license-audit: wrote docs/DEPENDENCY-LICENSES.md (${rows.length} packages, ${problems.length} needing review)`);
}
