// Seeded safety-rule mutations (QA-owned). Every entry breaks one safety rule in an isolated copy of the sources and names the real
// tests that must then fail with an assertion. Anchors must occur exactly once; a stale anchor is an ANCHOR_ERROR and fails the gate
// instead of silently dropping the control. `rebuild: true` recompiles the package first because the killing tests run the built worker.
const SPEC = "tests/accesslease.spec.ts";

export const MUTATIONS = [
  { name: "wildcard scopes accepted", rule: "AC-01 wildcard scopes are rejected", test: SPEC, grep: "scope and TTL policy",
    changes: [{ file: "src/domain/scopes.ts", find: "if (WILDCARD_CHARS.test(scope) || components.some((c) => WILDCARD_WORDS.has(c))) {", replace: "if (false) {" }] },
  { name: "admin-class scopes accepted", rule: "AC-01 admin scopes are rejected", test: SPEC, grep: "scope and TTL policy",
    changes: [{ file: "src/domain/scopes.ts", find: "if (components.some((c) => ADMIN_WORDS.has(c)) || ADMIN_SUBSTRINGS.some((s) => lower.includes(s))) {", replace: "if (false) {" }] },
  { name: "TTL hard maximum not enforced", rule: "AC-01 TTL over the policy maximum is rejected", test: SPEC, grep: "scope and TTL policy",
    changes: [{ file: "src/services/policy.ts", find: 'if (ttlSeconds > input.policy.max_ttl_seconds) throw unprocessable("ttl_exceeds_max"', replace: 'if (false) throw unprocessable("ttl_exceeds_max"' }] },
  { name: "approval not bound to the plan hash", rule: "AC-02 a changed request cannot be approved", test: SPEC, grep: "approval freshness",
    changes: [{ file: "src/services/leases.ts", find: 'if (!safeEqual(lease.plan_hash, data.plan_hash)) throw conflict("plan_hash_mismatch"', replace: 'if (false) throw conflict("plan_hash_mismatch"' }] },
  { name: "expired approval still issues", rule: "AC-02 an expired approval cannot issue access", test: SPEC, grep: "approval freshness",
    changes: [{ file: "src/workers/issue.ts", find: 'if ((checks.approval_expires_at as Date).getTime() <= now.getTime()) return refuse(tx, ctx, job, lease, "approval_expired", "approval expired before issuance");', replace: "void checks;" }] },
  { name: "native TTL not set on the provider role", rule: "AC-03 the provider enforces the TTL natively (VALID UNTIL)", test: SPEC, grep: "native TTL and issue ambiguity|real denial proof",
    changes: [{ file: "src/connectors/postgres-role.ts", find: " VALID UNTIL ${lit(request.expiresAt.toISOString())}`;", replace: "`;" }] },
  { name: "revoked recorded without verification", rule: "AC-04/05 REVOKED_VERIFIED requires independent verification", test: SPEC, grep: "revocation outage|expiry and closure",
    changes: [{ file: "src/workers/revoke.ts", find: 'const verified = errCode === null && steps.length > 0 && look?.state === "absent" && probe === "denied" && steps.every((s) => s.ok);', replace: "const verified = true;" }] },
  { name: "verification trusts the probe alone", rule: "AC-05 a surviving grant is not verified revocation", test: "tests/unit/backend/terminal-fence.test.ts", grep: "a surviving role is not verified",
    changes: [{ file: "src/workers/revoke.ts", find: 'const verified = errCode === null && steps.length > 0 && look?.state === "absent" && probe === "denied" && steps.every((s) => s.ok);', replace: 'const verified = errCode === null && steps.length > 0 && probe === "denied" && steps.every((s) => s.ok);' }] },
  { name: "overdue sweep skipped", rule: "AC-04/06 overdue grants are swept every pass", test: SPEC, grep: "restart sweep|expiry and closure",
    changes: [{ file: "src/workers/index.ts", find: "const sweep = await sweepOverdue(ctx);", replace: "const sweep = { expiredToRevoking: 0, overdueRecovered: 0, staleRequestsClosed: 0, jobsReclaimed: 0, at: ctx.clock().toISOString() };" }] },
  { name: "open sessions not terminated on revoke", rule: "AC-07 an already-open session does not survive revocation", test: SPEC, grep: "real denial proof",
    changes: [{ file: "src/connectors/postgres-role.ts", find: '"SELECT pid, pg_terminate_backend(pid) AS ok FROM pg_stat_activity WHERE usename = $1 AND pid <> pg_backend_pid()"', replace: '"SELECT pid, pg_terminate_backend(pid) AS ok FROM pg_stat_activity WHERE usename = $1 AND pid <> pg_backend_pid() AND false"' }] },
  { name: "credential not purged after retrieval", rule: "AC-07/09 credential delivery is one-time", test: SPEC, grep: "real denial proof",
    changes: [{ file: "src/services/leases.ts", find: 'await tx.query("UPDATE lease_secrets SET credential_ct = NULL, credential_retrieved_at = $2, purged_at = $2 WHERE lease_id = $1", [id, now]);', replace: 'await tx.query("UPDATE lease_secrets SET credential_retrieved_at = $2 WHERE lease_id = $1", [id, now]);' }] },
  { name: "CSRF check dropped", rule: "AC-12 mutations require a valid CSRF token", test: SPEC, grep: "workspace isolation",
    changes: [{ file: "src/api/common.ts", find: 'if (!csrf || !safeEqual(csrf, csrfFor(ctx, token))) throw fail("csrf_invalid", "Missing or invalid CSRF token");', replace: "void csrf;" }] },
  { name: "role checks disabled", rule: "AC-12 admin/operator/viewer roles are enforced", test: SPEC, grep: "workspace isolation|scope and TTL policy",
    changes: [{ file: "src/services/roles.ts", find: "if (RANK[principal.role] < RANK[minimum]) throw forbidden();", replace: "void RANK;" }] },
  { name: "workspace filter dropped on lease reads", rule: "AC-12 cross-workspace ids are 404", test: SPEC, grep: "workspace isolation",
    changes: [{ file: "src/services/leases.ts", find: '"SELECT * FROM leases WHERE workspace_id = $1 AND id = ANY($2::uuid[])"', replace: '"SELECT * FROM leases WHERE ($1::uuid IS NOT NULL) AND id = ANY($2::uuid[])"' }] },
  { name: "redaction disabled", rule: "AC-09 planted secrets never reach logs, exports or storage", test: SPEC, grep: "redaction and hostile input",
    changes: [{ file: "src/lib/redact.ts", find: "  let out = text;", replace: "  if (text) return text;\n  let out = text;" }] },
  { name: "HTML escaping disabled in the static report", rule: "AC-09 malicious HTML renders as text", test: SPEC, grep: "redaction and hostile input",
    changes: [{ file: "src/report/render.ts", find: "return value.replace(/[&<>\"'`]/g, (ch) => {", replace: "return value.replace(/(?!)/g, (ch) => {" }] },
  { name: "unconfirmed revocation presented as verified", rule: "AC-05 never a green revoked state for an unconfirmed revocation", test: SPEC, grep: "revocation outage",
    changes: [{ file: "src/report/status.ts", find: 'label: "REVOCATION UNCONFIRMED",\n    tone: "uncertain",', replace: 'label: "REVOCATION UNCONFIRMED",\n    tone: "verified",' }] },
  { name: "tampered bundle content accepted", rule: "AC-10 hash verification of every bundle file", test: SPEC, grep: "portability and corruption",
    changes: [{ file: "src/services/evidence.ts", find: "if (contentHash(doc) !== entry.sha256 || bytesOf(doc) !== entry.bytes) throw new BundleError(", replace: "if (false) throw new BundleError(" }] },
  { name: "modified migration does not stop readiness", rule: "AC-13 failed or modified migrations stop readiness", test: SPEC, grep: "restart and restore", rebuild: false,
    changes: [{ file: "src/db/migrate.ts", find: "const modified = files.find((f) => known.has(f.file) && known.get(f.file) !== f.checksum);", replace: "const modified = undefined as unknown as (typeof files)[number] | undefined;" }] },
  { name: "dead worker jobs never reclaimed", rule: "AC-13 a restarted worker reclaims leased jobs", test: SPEC, grep: "restart and restore", rebuild: true,
    changes: [
      { file: "src/services/jobs.ts", find: "OR (j.state = 'running' AND j.lease_until < $3))", replace: "OR (false))" },
      { file: "src/services/jobs.ts", find: "WHERE state = 'running' AND lease_until < $1\",", replace: "WHERE state = 'running' AND lease_until < $1 AND false\"," },
    ] },
];
